config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'oauth_callbacks' }

  scope constraints: lambda { |r| r.env['warden'].user.nil? } do
    root 'initials#index'
  end

  scope constraints: lambda { |r| !r.env['warden'].user.nil? } do
    root 'posts#tutor_index'
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  resources :initials, only: [:create, :index] do
    get :get_availability, on: :collection
    get :enter_page, on: :collection
  end

  resources :profiles

  resources :courses, shallow: true do
    resources :moduls do
      post :sort, on: :collection

      resources :topics do
        post :sort, on: :collection
        resources :topic_passages, only: [:update]
        resources :questions do
          resources :question_passages, only: [:create]
          resources :answers, only: [:destroy, :edit, :update]
        end
      end

      resources :essays do
        resources :essay_passages, only: [:new, :show, :create, :update] do
          patch :update_status, on: :member
        end
      end

      resources :tests do
        get :start, on: :member

        resources :test_passages, only: [:show] do
          patch :update_status, on: :member
        end
        resources :questions do
          resources :question_passages, only: [:create]
          resources :answers, only: [:destroy, :edit, :update]
        end
      end
    end
  end

  resources :tutor_infos, only: [:index, :update] do
    get :site_features, on: :collection
    get :diplomas, on: :collection
  end

  resources :weekly_digests, only: [:create, :destroy]
  resources :mailers, only: [:create]
  resources :preregistrations, only: [:new, :create]
  resources :searches, only: [:index]
  resources :attachments, only: :destroy
  resources :attendances
  resources :characteristics
  resources :progresses
  resources :feedbacks, except: [:show, :new]
  resources :course_passages, only: [:new, :create]
  resources :modul_passages, only: [:create]
  resources :notifications, only: [:index, :create, :update] do
    put :update_all, on: :collection
    delete :destroy_all, on: :collection
    post :send_for_all, on: :collection
  end

  resources :messages, only: [:create, :index, :destroy] do
    get :abonents, on: :collection
  end

  resources :posts, concerns: [:votable], shallow: true do
    resources :comments, concerns: [:votable], except: [:index, :show]

    get :tutor_index, on: :collection
    get :own_index, on: :collection
    get :guests_index, on: :collection
  end

  namespace :admin do
    resources :mainmenus, only: [:index]
    resources :one_time_passwords, only: [:new, :create]
  end

  mount ActionCable.server => '/cable'
end

app/models/characteristic.rb
class Characteristic < ApplicationRecord
  belongs_to :user
end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  authorize_resource

  def index
    @users = User.all
  end

  def edit
    @characteristic = user.characteristic
  end

  def update
    user.characteristic.update(characteristic_params)
    @characteristic = user.characteristic
  end

  def show
    redirect_to root_path unless current_user&.admin? || cookies[:parent]

    user

    @chart = Gchart.line(  size: '1000x300',
                          title: "График успеваемости",
                          bg: 'white',
                          bar_colors: '3f8ed9',
                          legend: 'количество набранных баллов по ЕГЭ',
                          axis_with_labels: [['x'], ['y']],
                          min_value: 0,
                          max_value: 100,
                          data: progress_points,
                          labels: progress_date
    )

    authorize! :read, Characteristic
  end

  private

  def user
    @user ||= User.find(params[:id])
  end

  def progress_points
    user.progresses.pluck(:points)
  end

  def progress_date
    user.progresses.pluck(:date)
  end

  def characteristic_params
    params.require(:characteristic).permit(:description)
  end
end

app/views/characteristics/_form_edit.html.slim
= form_with model: @characteristic, url: characteristic_path(@characteristic.user), method: :put, remote: true do |f|
  .form-group
    = f.text_area :description, class: 'form-control'
  .submit
    = f.submit 'Сохранить', class: 'btn btn-success'

app/views/characteristics/_message_to_tutor.html.slim
.message-to-tutor__block.row.align-items-center
  .col = link_to mi.email.css_class('md-36 stub white'), '#', data: {toggle: 'modal', target: '#messageToTutorModal'}

app/views/characteristics/_modal_attend.html.slim
.modal.fade aria-hidden="true" aria-labelledby="attendFullModalLabel" role="dialog" tabindex="-1" id="attendFullModal-#{attend.id}"
  .modal-dialog.modal-dialog-centered role="document"
    .modal-content
      .modal-header
        h5#attendFullModalLabel.modal-title = "Посещение за #{I18n.localize attend.date, format: '%-d %B'}"
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
      .modal-body
        = attend.description
      - if can?(:update, attend)
        .modal-footer.d-flex.justify-content-between
          = link_to 'Редактировать', edit_attendance_path(attend), class:"btn btn-primary"
          = link_to 'Удалить', attendance_path(attend), method: :delete, remote: true, class:"btn btn-danger"

app/views/characteristics/_modal_message_to_tutor.html.slim
#messageToTutorModal.modal.fade aria-hidden="true" aria-labelledby="messageToTutorModalLabel" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-header.bg-dark
        h5#messageToTutorModalLabel.modal-title.text-light = 'Написать репетитору'
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span.text-light aria-hidden="true"  &times;
      .modal-body
        / h3.pull-right = 'Что говорят ученики'
        .form_message-to-tutor
          = form_tag '/mailers', remote: true do
            = text_area_tag 'message', '', class: 'form-control mb_1', placeholder: 'Введите сообщение...', style: "height: 300px"
            = submit_tag 'Отправить сообщение', class: 'btn btn-success'

app/views/characteristics/_modal_weekly_digest.html.slim
#weeklyDigestModal.modal.fade aria-hidden="true" aria-labelledby="weeklyDigestModalLabel" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-header.bg-dark
        h5#weeklyDigestModalLabel.modal-title.text-light = 'Подписаться на рассылку'
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span.text-light aria-hidden="true"  &times;
      .modal-body
        .errors-weekly-digest
        .small_text.mb-2 = t('.explanation', user: @user.full_name)
        = link_to 'Отписаться от рассылки', weekly_digest_path(@user), method: :delete, class: 'mb-2 badge badge-light', remote: true
        .form_subscribe-weekly-digest
          = form_tag '/weekly_digests', remote: true do
            = text_field_tag 'email', '', class: 'form-control mb_1', placeholder: 'Введите Email...'
            = submit_tag 'Подписаться на рассылку', class: 'btn btn-success'

app/views/characteristics/_weekly_digest.html.slim
.weekly-digest__block.row.align-items-center
  .col = link_to mi.notifications.css_class('md-36 stub white'), '#', data: {toggle: 'modal', target: '#weeklyDigestModal'}

app/views/characteristics/edit.js.erb
$('.characteristic-description__edit-form').html('<%= j render 'form_edit', local: @characteristic %>');

app/views/characteristics/index.html.slim
table.table.table-users.table-bordered
  thead.thead-dark
    tr
      th scope='col' Характеристики учеников
  tbody
    - @users.each do |user|
      tr
        td
          = link_to user.full_name, characteristic_path(user), class: 'badge badge-light'

app/views/characteristics/show.html.slim
.bg-dark.p-1.br-10.d-flex.justify-content-between
  h1.text-white = @user.full_name
  div
    h6.mr_1.blue = 'Идентификатор:'
    h5.white = @user.identify_name

.characteristic-description
  h6.text-secondary = 'Общая характеристика:'
  p = @user&.characteristic&.description

- if can?(:manage, :all)
  = link_to 'Редактировать общую характеристику', edit_characteristic_path(@user), remote: true, class: 'btn btn-outline-primary'
  .characteristic-description__edit-form

.d-flex.mt-3.mb-3
  .weekly-digest-mobile__block.row.align-items-center
    .col = button_to 'Подписаться на рассылку', '#', data: {toggle: 'modal', target: '#weeklyDigestModal'}, class: 'btn btn-outline-info stub'
  .message-to-tutor-mobile__block.row.align-items-center
    .col = button_to 'Написать репетитору', '#', data: {toggle: 'modal', target: '#messageToTutorModal'}, class: 'btn btn-outline-info stub'

.chart-image-full.mb-5vh = image_tag @chart
.chart-image-mobile = link_to 'График успеваемости', (image_path @chart), class: 'btn btn-info', target: '_blank'

- if can?(:manage, :all)
  .progresses-list.mr_1_for_child.mb-5vh
    h5 = 'Ссылки на редактирование любой успеваемости:'
    - @user.progresses.each do |progress|
      = link_to '', edit_progress_path(progress), class: 'progress-square', title: "#{progress.date}"

.attendance-list.mr_1_for_child
  h3.text-secondary = 'Даты посещения:'
  - if @user.attendances
    - @user.attendances.order(date: :desc).each do |attend|
      = link_to  '#', class:"attend_small mb_1 attend-#{attend.id}", style:"background: #{attend.color}",
                                                                     data: { id: attend.id, toggle: 'modal', target: "#attendFullModal-#{attend.id}" } do
        .attend-date = "#{I18n.localize attend.date, format: '%-d'}"
        .attend-month = "#{I18n.localize attend.date, format: '%B'}"
      = render 'modal_attend', attend: attend

= render 'weekly_digest'
= render 'modal_weekly_digest'
= render 'message_to_tutor'
= render 'modal_message_to_tutor'

app/views/characteristics/update.js.erb
$('.characteristic-description p').html("<%= @characteristic.description %>")