config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'oauth_callbacks' }

  scope constraints: lambda { |r| r.env['warden'].user.nil? } do
    root 'initials#index'
  end

  scope constraints: lambda { |r| !r.env['warden'].user.nil? } do
    root 'posts#tutor_index'
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  resources :initials, only: [:create, :index] do
    get :get_availability, on: :collection
    get :enter_page, on: :collection
  end

  resources :profiles

  resources :courses, shallow: true do
    resources :moduls do
      post :sort, on: :collection

      resources :topics do
        post :sort, on: :collection
        resources :topic_passages, only: [:update]
        resources :questions do
          resources :question_passages, only: [:create]
          resources :answers, only: [:destroy, :edit, :update]
        end
      end

      resources :essays do
        resources :essay_passages, only: [:new, :show, :create, :update] do
          patch :update_status, on: :member
        end
      end

      resources :tests do
        get :start, on: :member

        resources :test_passages, only: [:show] do
          patch :update_status, on: :member
        end
        resources :questions do
          resources :question_passages, only: [:create]
          resources :answers, only: [:destroy, :edit, :update]
        end
      end
    end
  end

  resources :tutor_infos, only: [:index, :update] do
    get :site_features, on: :collection
    get :diplomas, on: :collection
  end

  resources :weekly_digests, only: [:create, :destroy]
  resources :mailers, only: [:create]
  resources :preregistrations, only: [:new, :create]
  resources :searches, only: [:index]
  resources :attachments, only: :destroy
  resources :attendances
  resources :characteristics
  resources :progresses
  resources :feedbacks, except: [:show, :new]
  resources :course_passages, only: [:new, :create]
  resources :modul_passages, only: [:create]
  resources :notifications, only: [:index, :create, :update] do
    put :update_all, on: :collection
    delete :destroy_all, on: :collection
    post :send_for_all, on: :collection
  end

  resources :messages, only: [:create, :index, :destroy] do
    get :abonents, on: :collection
  end

  resources :posts, concerns: [:votable], shallow: true do
    resources :comments, concerns: [:votable], except: [:index, :show]

    get :tutor_index, on: :collection
    get :own_index, on: :collection
    get :guests_index, on: :collection
  end

  namespace :admin do
    resources :mainmenus, only: [:index]
    resources :one_time_passwords, only: [:new, :create]
  end

  mount ActionCable.server => '/cable'
end

app/models/essay_passage.rb
class EssayPassage < ApplicationRecord
  belongs_to :user
  belongs_to :essay

  validates :body, presence: true
end

app/controllers/essay_passages_controller.rb
class EssayPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :essay_passage, only: [:new, :show]

  authorize_resource

  def new
  end

  def show
  end

  def create
    @essay_passage = essay.essay_passages.new(essay_passage_params)
    @essay_passage.user = current_user
    @essay_passage.save unless essay.essay_passage(current_user)
    redirect_to essay_path(essay)
  end

  def update
    essay_passage.update(essay_passage_params)
  end

  def update_status
    essay_passage.update(status: true)
    Services::SendNotificationService.new('Ваше эссе проверено', essay_path(essay_passage.essay), essay_passage.user, current_user).send
    Services::CharacteristicChangeService.new(essay_passage.user, requests, params[:essay_passage][:points], profile_path(essay_passage.user)).change
    head :ok
  end

  private

  def essay_passage
    @essay_passage ||= params[:id] ? EssayPassage.find(params[:id]) : essay.essay_passages.new
  end

  def essay
    @essay ||= Essay.find(params[:essay_id])
  end

  def requests
    request.referrer.split('/')[3]
  end

  def essay_passage_params
    params.require(:essay_passage).permit(:body)
  end
end

app/views/essay_passages/_essay_passage.html.slim
= @essay_passage.body.html_safe

app/views/essay_passages/_essay_passage_full.html.slim
- if @essay_passage
  .essay-edit__button = button_tag 'Редактировать эссе', remote: true, class: 'btn btn-primary btn-lg'
- else
  .essay-new__button = button_to 'Написать эссе', new_essay_essay_passage_path(@essay), method: :get, remote: true, class: 'btn btn-primary btn-lg'

.essay-passage__body = @essay_passage&.body&.html_safe

- unless @essay_passage
  .essay_passages__form_new.hidden
    .essay-passage__fields
      = form_with model: EssayPassage.new, method: :post, url: essay_essay_passages_path(@essay) do |f|
        .field
          = f.text_area :body, :class => "tinymce", rows: 25, cols: 120
          = tinymce content_css: asset_path('application.css')
        .submit
          = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/essay_passages/_form_edit.html.slim
.essay-passage__fields
  = form_with model: @essay_passage, method: :put, url: essay_passage_path(@essay_passage), remote: true do |f|
    .field
      = f.text_area :body, :class => "tinymce", rows: 25, cols: 120
      = tinymce content_css: asset_path('application.css')
    .submit
      = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/essay_passages/_form_new.html.slim
.essay-passage__fields
  = form_with model: essay_passage, method: :post, url: essay_essay_passages_path(@essay) do |f|
    .field
      = f.text_area :body, :class => "tinymce", rows: 25, cols: 120
      = tinymce content_css: asset_path('application.css')
    .submit
      = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/essay_passages/new.js.erb
$('.essay_passages__form_new').show(500)
$('.essay-new__button').hide(500)

app/views/essay_passages/show.html.slim
.essay
  h3 = @essay_passage.essay.title

.essay-passage
  = render 'essay_passages/essay_passage_full'

.essay_passages__form_edit.hidden = render 'essay_passages/form_edit' if @essay_passage

- if can?(:manage, :all)
  .essay-passage-ready-form
    .essay-passage-ready-form__fields
      = form_with model: @essay_passage, method: :patch, url: update_status_essay_passage_path(@essay_passage), class: 'form-inline', remote: true do |f|
        .form-group.mb-2
          = f.number_field :points, class: 'form-control', placeholder: 'Очки'
        .mb-2
          = f.submit 'Уведомить ученика об окончании проверки', class: 'btn btn-success check-essay__button'

app/views/essay_passages/update.js.erb
$('.flash-block').html('<%= render 'shared/errors', resource: @essay_passage %>');

<% if !@essay_passage.errors.present? %>
  $('.essay-passage__body').html('<%= j render 'essay_passages/essay_passage', locale: @essay_passage %>')
  $('.essay_passages__form_edit').hide(500)
  $('.essay-passage__body').show(500)
<% end %>