config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'oauth_callbacks' }

  scope constraints: lambda { |r| r.env['warden'].user.nil? } do
    root 'initials#index'
  end

  scope constraints: lambda { |r| !r.env['warden'].user.nil? } do
    root 'posts#tutor_index'
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  resources :initials, only: [:create, :index] do
    get :get_availability, on: :collection
    get :enter_page, on: :collection
  end

  resources :profiles

  resources :courses, shallow: true do
    resources :moduls do
      post :sort, on: :collection

      resources :topics do
        post :sort, on: :collection
        resources :topic_passages, only: [:update]
        resources :questions do
          resources :question_passages, only: [:create]
          resources :answers, only: [:destroy, :edit, :update]
        end
      end

      resources :essays do
        resources :essay_passages, only: [:new, :show, :create, :update] do
          patch :update_status, on: :member
        end
      end

      resources :tests do
        get :start, on: :member

        resources :test_passages, only: [:show] do
          patch :update_status, on: :member
        end
        resources :questions do
          resources :question_passages, only: [:create]
          resources :answers, only: [:destroy, :edit, :update]
        end
      end
    end
  end

  resources :tutor_infos, only: [:index, :update] do
    get :site_features, on: :collection
    get :diplomas, on: :collection
  end

  resources :weekly_digests, only: [:create, :destroy]
  resources :mailers, only: [:create]
  resources :preregistrations, only: [:new, :create]
  resources :searches, only: [:index]
  resources :attachments, only: :destroy
  resources :attendances
  resources :characteristics
  resources :progresses
  resources :feedbacks, except: [:show, :new]
  resources :course_passages, only: [:new, :create]
  resources :modul_passages, only: [:create]
  resources :notifications, only: [:index, :create, :update] do
    put :update_all, on: :collection
    delete :destroy_all, on: :collection
    post :send_for_all, on: :collection
  end

  resources :messages, only: [:create, :index, :destroy] do
    get :abonents, on: :collection
  end

  resources :posts, concerns: [:votable], shallow: true do
    resources :comments, concerns: [:votable], except: [:index, :show]

    get :tutor_index, on: :collection
    get :own_index, on: :collection
    get :guests_index, on: :collection
  end

  namespace :admin do
    resources :mainmenus, only: [:index]
    resources :one_time_passwords, only: [:new, :create]
  end

  mount ActionCable.server => '/cable'
end

app/views/shared/_admin_sidebar_left.html.slim
.container-fluid.pl-0.admin-sidebar-left
  .row
    .col-auto.admin-sidebar-left__small
      .col-auto.pl-0 = link_to mi.account_balance.css_class('md-36 stub white'), '#'

    .col-auto.admin-sidebar-left__full.hidden
      p = link_to 'Создать одноразовый пароль', new_admin_one_time_password_path, class: 'link-call-password-form'
      p = link_to 'Добать ученика к Курсу', new_course_passage_path
      p = link_to 'Добавить посещение', new_attendance_path
      p = link_to 'Редактировать свой профиль', tutor_infos_path
      p = link_to 'Посты для гостей', guests_index_posts_path
      p = link_to 'Характеристики учеников', characteristics_path
      p = link_to 'Добавить прогресс ученика', new_progress_path

app/views/shared/_button_back.html.slim
.container-fluid.pl-0.button_back
  .row
    .col-auto.button_back__small
      .col-auto.pl-0 = link_to mi.keyboard_return.css_class('md-36 white'), :back

app/views/shared/_dropdown-profile-menu.html.slim
.dropdown.nav-dropdown-profile
  = image_tag current_user.nav_avatar, class: 'dropdown-toggle handle nav_avatar', id: "dropdownProfileMenuLink",
          data: { toggle: "dropdown" },  aria: { haspopup: "true", expanded: "false" }

  .dropdown-menu.dropdown-menu-right.text-1rem aria-labelledby="dropdownProfileMenuLink"
    = link_to 'Мой профиль', profile_path(current_user), class: 'dropdown-item'
    = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'dropdown-item'

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  .alert.resource-errors
    b = t("errors.messages.not_saved",
            count: resource.errors.count,
            resource: resource.class.model_name.human.downcase)
    -resource.errors.full_messages.each do |message|
      p = message

app/views/shared/_footer.html.slim
nav.footer.navbar-dark.bg-dark.box-shadow-nav

app/views/shared/_info.html.slim
.alert.alert-success
  p = resource

app/views/shared/_nav.html.slim
/ .pos-f-t
/   .collapse#navbarToggleExternalContent
/     .bg-dark.p-4.d-flex.justify-content-between
/       .nav-profile-info
/         h5.text-white.h4.user-icon data-user-id="#{current_user&.id}" = current_user&.full_name
/         .text-muted.text-shadow-black-for-child.d-flex
/           h1.align-self-end.mb-0.mr-1 = current_user&.characteristic&.points
/           span.align-self-end = 'баллов' if current_user&.characteristic&.points
/         .text-muted.text-shadow-black-for-child
/           b = current_user&.characteristic&.rank
/       .d-flex.justify-content-end
/         h6.mr_1.blue = 'Идентификатор:' if current_user
/         .mr-auto
/           h5.white = current_user&.identify_name

nav.navbar.navbar-base
  .d-flex.mr_5_for_child
    / - if user_signed_in?
    /   = button_tag '', type: "button", class:'navbar-toggler', data: { toggle: "collapse", target: "#navbarToggleExternalContent" },
    /                aria: {  controls: "navbarToggleExternalContent", expanded: "false", label: "Toggle navigation" }
        span.navbar-toggler-icon
    .title-examtutor
      = link_to 'ExamtutoR', root_path

  - if current_user
    .nav__right-block
      .search-block.row.mr-1
        .search_field = render 'shared/search_field'
      = render 'shared/notification'
      = render 'shared/dropdown-profile-menu'

app/views/shared/_notification.html.slim
.notifications-dropdown.btn-group.user-icon data-user-id="#{current_user&.id}"
  .btn-group.dropleft role="group"
    = button_tag '' , class: 'btn btn-secondary dropdown-toggle dropdown-toggle-split badge', id:"dropdownMenuButton", data:{ toggle:"dropdown" }, aria:{ haspopup: "true", expanded: "false"}
      span class='sr-only'
        = 'Toggle Dropleft'
    .dropdown-menu.dropdown-menu__notifications aria-labelledby="dropdownMenuButton"
      - notifications.each do |notification|
        p = link_to notification.title, notification_path(id: notification, link: notification.link), method: :patch, class: 'badge badge-warning'
  = button_tag '', class:'btn stub notify-button', onclick:"location.href='/notifications'"
    - if notifications.present?
      = link_to mi.email.css_class('md-24 stub red'), '#'
    - else
      = 'Уведомления'

app/views/shared/_search_field.html.slim
= form_tag(searches_path, method: :get) do
  = select_tag :category, options_for_select(category_list), class: 'btn btn-outline-secondary btn-sm'
  = text_field_tag :search, '', placeholder: 'Поиск по сайту'
  = submit_tag 'Найти', class: 'btn btn-outline-secondary btn-sm'

app/views/shared/_sidebar_left.html.slim
.container-fluid.pl-0.sidebar-left
  .row
    .col-auto.sidebar-left__small
      .col-auto.pl-0 = link_to mi.undo.css_class('md-24 black'), :back
      .col-auto.pl-0 = link_to mi.school.css_class('md-24 stub black'), '#'
      .col-auto.pl-0 = link_to mi.account_box.css_class('md-24 stub black'), '#'
      .col-auto.pl-0 = link_to mi.library_books.css_class('md-24 stub black'), '#'
      .col-auto.pl-0 = link_to mi.chat_bubble_outline.css_class('md-24 stub black'), '#'
      .col-auto.pl-0 = link_to mi.people.css_class('md-24 stub black'), '#'
      / .col-auto.pl-0 = link_to mi.thumb_up_alt.css_class('md-24 stub black'), '#'
      - if can?(:manage, :all)
        hr
        .col-auto.pl-0 = link_to mi.vpn_key.css_class('md-24 stub black'), '#'
        .col-auto.pl-0 = link_to mi.person_add.css_class('md-24 stub black'), '#'
        .col-auto.pl-0 = link_to mi.person_add.css_class('md-24 stub black'), '#'
        .col-auto.pl-0 = link_to mi.person_add.css_class('md-24 stub black'), '#'
        .col-auto.pl-0 = link_to mi.remove_red_eye.css_class('md-24 stub black'), '#'
        .col-auto.pl-0 = link_to mi.library_books.css_class('md-24 stub black'), '#'
        .col-auto.pl-0 = link_to mi.insert_chart.css_class('md-24 stub black'), '#'

    .col-auto.sidebar-left__full.hidden
      p = link_to 'НАЗАД', :back
      p = link_to 'КУРСЫ', courses_path
      p = link_to 'МОЙ ПРОФИЛЬ', profile_path(current_user)
      p = link_to 'СТАТЬИ', posts_path
      p = link_to 'СООБЩЕНИЯ', abonents_messages_path
      p = link_to 'СТУДЕНТЫ', profiles_path
      / p = link_to 'ОТЗЫВЫ', feedbacks_path
      - if can?(:manage, :all)
        hr
        p = link_to 'ДОБАВИТЬ ПАРОЛЬ ОДНОРАЗОВЫЙ', new_admin_one_time_password_path, class: 'link-call-password-form'
        p = link_to 'ДОБАВИТЬ УЧЕНИКА К КУРСУ', new_course_passage_path
        p = link_to 'ДОБАВИТЬ ПОСЕЩЕНИЕ', new_attendance_path
        p = link_to 'ДОБАВИТЬ ПРОГРЕСС УЧЕНИКА', new_progress_path
        p = link_to 'РЕДАКТИРОВАТЬ СВОЙ ПРОФИЛЬ', tutor_infos_path
        p = link_to 'СТАТЬИ ДЛЯ ГОСТЕЙ', guests_index_posts_path
        p = link_to 'ХАРАКТЕРИСТИКИ УЧЕНИКА', characteristics_path

app/views/shared/_vote_links.html.slim
.text-center = link_to mi.thumb_up_alt.css_class('md-18 stub grey'), polymorphic_url([:vote_up, resource]), class: 'vote vote-up',
        remote: true, method: :post, data: { type: :json } if can?(:vote_up, resource)
.text-center.rating
  b = resource.rating
.text-center = link_to mi.thumb_down_alt.css_class('md-18 stub grey'), polymorphic_url([:vote_down, resource]), class: 'vote vote-down',
        remote: true, method: :post, data: { type: :json } if can?(:vote_down, resource)

app/views/shared/_yandex-metrika.html.slim
script[type="text/javascript"]
  |  (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)}; m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)}) (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym"); ym(53565328, "init", { clickmap:true, trackLinks:true, accurateTrackBounce:true });
noscript
  div
    img[src="https://mc.yandex.ru/watch/53565328" style="position:absolute; left:-9999px;" alt=""]