config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'oauth_callbacks' }

  scope constraints: lambda { |r| r.env['warden'].user.nil? } do
    root 'initials#index'
  end

  scope constraints: lambda { |r| !r.env['warden'].user.nil? } do
    root 'posts#tutor_index'
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
    end
  end

  resources :initials, only: [:create, :index] do
    get :get_availability, on: :collection
    get :enter_page, on: :collection
  end

  resources :profiles

  resources :courses, shallow: true do
    resources :moduls do
      post :sort, on: :collection

      resources :topics do
        post :sort, on: :collection
        resources :topic_passages, only: [:update]
        resources :questions do
          resources :question_passages, only: [:create]
          resources :answers, only: [:destroy, :edit, :update]
        end
      end

      resources :essays do
        resources :essay_passages, only: [:new, :show, :create, :update] do
          patch :update_status, on: :member
        end
      end

      resources :tests do
        get :start, on: :member

        resources :test_passages, only: [:show] do
          patch :update_status, on: :member
        end
        resources :questions do
          resources :question_passages, only: [:create]
          resources :answers, only: [:destroy, :edit, :update]
        end
      end
    end
  end

  resources :tutor_infos, only: [:index, :update] do
    get :site_features, on: :collection
    get :diplomas, on: :collection
  end

  resources :weekly_digests, only: [:create, :destroy]
  resources :mailers, only: [:create]
  resources :preregistrations, only: [:new, :create]
  resources :searches, only: [:index]
  resources :attachments, only: :destroy
  resources :attendances
  resources :characteristics
  resources :progresses
  resources :feedbacks, except: [:show, :new]
  resources :course_passages, only: [:new, :create]
  resources :modul_passages, only: [:create]
  resources :notifications, only: [:index, :create, :update] do
    put :update_all, on: :collection
    delete :destroy_all, on: :collection
    post :send_for_all, on: :collection
  end

  resources :messages, only: [:create, :index, :destroy] do
    get :abonents, on: :collection
  end

  resources :posts, concerns: [:votable], shallow: true do
    resources :comments, concerns: [:votable], except: [:index, :show]

    get :tutor_index, on: :collection
    get :own_index, on: :collection
    get :guests_index, on: :collection
  end

  namespace :admin do
    resources :mainmenus, only: [:index]
    resources :one_time_passwords, only: [:new, :create]
  end

  mount ActionCable.server => '/cable'
end

app/controllers/initials_controller.rb
class InitialsController < ApplicationController
  skip_authorization_check
  layout 'initial', only: [:index]

  def index
    @user = User.new
  end

  def get_availability
    if User.find_by(id: identify_id, last_name: identify_name)
      cookies[:parent] = identify_id
      redirect_to characteristic_path(identify_id)
    else
      flash[:alert] = 'Идентификатор набран неверно'
      redirect_to enter_page_initials_path
    end
  end

  def enter_page
    @user = User.new
  end

  def create
    password = params[:preregistration_pass]
    one_time_password = OneTimePassword.find_by_pass_word(password)

    if one_time_password
      cookies[:pre_password] = password
      one_time_password.destroy

      redirect_to new_user_registration_path, notice: 'Успешно!'
    else
      redirect_to enter_page_initials_path, alert: 'Доступ закрыт'
    end
  end

  private

  def identify_full
    params[:identify_name][0]
  end

  def identify_id
    identify_full.split('-').last
  end

  def identify_name
    identify_full.split('-').first
  end
end

app/views/initials/_dropdown-initial-menu.html.slim
.btn-group
  = button_tag 'Информация', class: 'btn button-blue dropdown-toggle', id: "dropdownInitialMenu",
          data: { toggle: "dropdown" },  aria: { haspopup: "true", expanded: "false" }
  .dropdown-menu aria-labelledby='dropdownInitialMenu'
    = link_to 'О себе', tutor_infos_path, class: 'dropdown-item'
    = link_to 'Авторские статьи', guests_index_posts_path, class: 'dropdown-item'
    = link_to 'Возможности платформы Examtutor.ru', site_features_tutor_infos_path, class: 'dropdown-item'

app/views/initials/_english_block.html.slim
.english-block
  .title.font-helvetica.d-flex.justify-content-center.align-items-center
    = 'Английский язык'
  .text.pl-3.mt-2
    b = "ОГЭ по английскому языку"
  .text.pl-3
    b = "ЕГЭ по английскому языку"
  .text.pl-3
    b = "Опыт: #{ Time.current.year - 2013 } лет"
  .text.p-3
    b = t('.english_description')

app/views/initials/_feedback-text.html.slim
.feedback-text
  .avatar = image_tag user.nav_avatar, class: 'handle feedback_avatar'
  .name
    b = user.full_name
  .text
    p = user.feedback.body

app/views/initials/_feedback.html.slim
.feedback-block
  .feedback-title.font-helvetica = 'Что говорят наши ученики'
  .feedback-all__button = button_tag 'Посмотреть все отзывы', class: 'btn stub', data: {toggle: 'modal', target: '#feedbacksAllModal'}
  = render 'modal_feedbacks-all'
  .d-flex.justify-content-center
    .feedback_slider.row.align-items-end.justify-content-center
      .carousel.slide id="carouselFeedbackIndicators" data-ride="carousel"
        ol.carousel-indicators
          li data-target="#carouselFeedbackIndicators" data-slide-to="0" class="active"
          - (Feedback.approved.count-1).times do |index|
            li data-target="#carouselFeedbackIndicators" data-slide-to="#{index+1}"
          end
        .carousel-inner
          - Feedback.approved.each do |feedback|
            - active = (feedback == Feedback.first) ? "active" : ''
            .carousel-item class="#{active}"
              .d-block.w-100
                / = image_tag('slide_one.png')
                = render 'feedback-text', user: feedback.user
        a.carousel-control-prev href="#carouselFeedbackIndicators" role="button" data-slide="prev"
          span.carousel-control-prev-icon aria-hidden="true"
          span.sr-only
        a.carousel-control-next href="#carouselFeedbackIndicators" role="button" data-slide="next"
          span.carousel-control-next-icon aria-hidden="true"
          span.sr-only

app/views/initials/_history_block.html.slim
.history-block
  .title.font-helvetica.d-flex.justify-content-center.align-items-center
    = 'История'
  .text.pl-3.mt-2
    b = "ЕГЭ по истории"
  .text.pl-3
    b = "ОГЭ по истории"
  .text.pl-3
    b = "Опыт: #{ Time.current.year - 2012 } лет"
  .text.p-3
    b = t('.history_description')

app/views/initials/_modal_parent_enter.html.slim
#parentEnterModal.modal.fade aria-hidden="true" aria-labelledby="pupilEnterModalLabel" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-header.bg-dark
        h5#pupilEnterModalLabel.modal-title.text-white = 'Вход для родителя'
        button.close.text-white aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
      .modal-body
        h3.pull-right = 'Введите идентификатор'
        = form_tag  'get_availability', method: 'get'
          .form-group
            = text_field :identify_name, '', autofocus: true, autocomplete: "Иванов-53", class: 'form-control', placeholder: 'Иванов-53'
            small class="form-text text-muted"
              = 'Идентификатор ученика. Указан в профиле ученика на его странице. Или узнайте у репетитора.'

          .actions
            = submit_tag 'Войти', class: 'btn btn-primary parent-submit'

app/views/initials/_modal_pupil_enter.html.slim
#pupilEnterModal.modal.fade aria-hidden="true" aria-labelledby="pupilEnterModalLabel" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        h5#pupilEnterModalLabel.modal-title = t('.header')
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
      .modal-body
        h2
          = t('.log_in')
          - if cookies[:pre_password]
            .display-flex.mr_1_for_child
              = link_to image_tag('vk.png'), '/users/auth/vkontakte'
              = link_to image_tag('fb.png'), '/users/auth/facebook'
              = link_to image_tag('github.png'), '/users/auth/github'

        = form_for(@user, as: @user, url: session_path(@user)) do |f|
          .form-group
            .field
              = f.label :email
              br
              = f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control', placeholder: 'Enter email'
          .form-group
            .field
              = f.label :password
              br
              = f.password_field :password, autocomplete: "current-password", class: 'form-control', placeholder: 'Enter password'
          .actions
            = f.submit t('.log_in'), class: 'btn btn-primary pupil-submit'
        / = render "devise/shared/links"
        = link_to "Забыли пароль?", new_password_path('user'), class: 'badge badge-light mb-1'
        = link_to "Не пришли инструкции по подтверждению?", new_confirmation_path('user'), class: 'badge badge-light mb-1'

      .modal-footer
        .modal-footer__registration-button__block
          = button_tag t('.sign_up'), class: 'btn btn-info modal-footer__registration-button'
        = form_tag '/initials', class: 'hidden modal-footer__registration-form' do
          .modal-footer__password-form
            .mr_1 = text_field_tag 'preregistration_pass', '', class: 'form-control', placeholder: t('.enter_password')
            div = submit_tag t('.confirm'), class: 'btn btn-primary'

app/views/initials/_russian_block.html.slim
.russian-block
  .title.font-helvetica.d-flex.justify-content-center.align-items-center
    = 'Русский язык'
  .text.pl-3.mt-2
    b = "ЕГЭ по русскому языку"
  .text.pl-3
    b = "Опыт: #{ Time.current.year - 2012 } лет"
  .text.p-3
    b = t('.russian_description')

app/views/initials/_slider-text-1.html.slim
= link_to '', class: 'stub' do
  .row.justify-content-center
    .slider-text.font-helvetica = 'Индивидуальные занятия'
  .row.justify-content-center
    .slider-text.font-helvetica = 'или'
  .row.justify-content-center
    .slider-text.font-helvetica = 'занятия в паре'

app/views/initials/_slider-text-3.html.slim
= link_to '', class: 'stub' do
  .row.justify-content-center
    .slider-text.font-helvetica = 'Только'
  .row.justify-content-center
    .slider-text.font-helvetica = 'в городе'
  .row.justify-content-center
    .slider-text.font-helvetica = 'Таганроге'

app/views/initials/_slider.html.slim
.initial_slider
  .carousel.slide id="carouselExampleIndicators" data-ride="carousel"
    / ol.carousel-indicators
    /   li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"
    /   li data-target="#carouselExampleIndicators" data-slide-to="1"
    /   li data-target="#carouselExampleIndicators" data-slide-to="2"
    .carousel-inner
      .carousel-item.active
        .d-block.w-100
          / = image_tag('slide_one.png')
          = render 'slider-text-1'
      .carousel-item
        .d-block.w-100
          / = image_tag('slide_two.png')
          = render 'slider-text-2'
      .carousel-item
        .d-block.w-100
          / = image_tag('slide_three.png')
          = render 'slider-text-3'
    / a.carousel-control-prev href="#carouselExampleIndicators" role="button" data-slide="prev"
    /   span.carousel-control-prev-icon aria-hidden="true"
    /   span.sr-only
    / a.carousel-control-next href="#carouselExampleIndicators" role="button" data-slide="next"
    /   span.carousel-control-next-icon aria-hidden="true"
    /   span.sr-only

app/views/initials/_social_block.html.slim
.social-block
  .title.font-helvetica.d-flex.justify-content-center.align-items-center
    = 'Обществознание'
  .text.pl-3.mt-2
    b = "ЕГЭ по обществознанию"
  .text.pl-3
    b = "ОГЭ по обществознанию"
  .text.pl-3
    b = "Опыт: #{ Time.current.year - 2012 } лет"
  .text.p-3
    b = t('.social_description')

app/views/initials/index1.html.slim
.initial
  .initial__one
    .dropdown
      = render 'dropdown-initial-menu'
    .initial__one__title.mb-5vh
      .title.row.font-helvetica.d-flex.justify-content-center.mb-5vh
        = t('.title')
      .title-text.row.d-flex.justify-content-center.mr_1_for_child.mb-5vh
        = link_to 'Истории', '#', class: 'badge badge-pill badge-light stub history-button'
        = link_to 'Обществознанию', '#', class: 'badge badge-pill stub badge-light social-button'
        = link_to 'Русскому языку', '#', class: 'badge badge-pill stub badge-light russian-button'
        = link_to 'Английскому языку', '#', class: 'badge badge-pill stub badge-light english-button'

      .title-text.row.d-flex.justify-content-center
        = image_tag url_for(TutorInfo.first.initial_profile_photo), class: 'initial_profile_photo' if TutorInfo.first

    = render 'slider'
    = render 'phone-number'

  .initial__registration-block
    .initial__registration-block__button-pupil.mr_1
      = button_tag t('.pupil_enter'), class: 'pupil-enter-button btn', data: {toggle: 'modal', target: '#pupilEnterModal'}, remote: true
    = render 'modal_pupil_enter'
    .initial__registration-block__button-parent
      = button_tag t('.parent_enter'), class: 'parent-enter-button btn', data: {toggle: 'modal', target: '#parentEnterModal'}, remote: true
    = render 'modal_parent_enter'
  .initial__two.mt-3
    .subject.ml-3.mr-3 = render 'history_block'
    .d-flex.justify-content-end.ml-3.mr-3
      .subject = render 'social_block'
    .subject.ml-3.mr-3 = render 'russian_block'
    .d-flex.justify-content-end.ml-3.mr-3
      .subject = render 'english_block'
  .initial__three
    = render 'feedback'
    = render 'requirements'
    = render 'footer-phone-number_block'